
[tasks.doc-katex]
watch = true
env = { "RUSTDOCFLAGS" = "--html-in-header  katex-header.html" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.all]
dependencies = [
    "docs",
    "doc-katex",
]